name: Reivew My Code, OpenCode!
description:
  LLM-powered code reviews via OpenCode. Reviews like a real dev - argue in
  comments, ask questions, fix issues.
author: Toms Jansons

branding:
  icon: user-check
  color: orange

inputs:
  opencode_auth_json:
    description:
      'OpenCode authentication JSON for LLM provider access. Must be a valid
      JSON string containing provider credentials. For API key auth use {"type":
      "api", "key": "sk-..."}. For OAuth use {"type": "oauth", ...oauth fields}.
      Examples: {"openrouter": {"type": "api", "key": "sk-..."}}, {"anthropic":
      {"type": "oauth"}}, {"openai": {"type": "api", "key": "sk-..."}}. Note:
      OAuth providers require additional configuration in OpenCode.'
    required: true
  model:
    description:
      'LLM model to use. Specify the exact model string as required by your
      provider. Examples: "openrouter/anthropic/claude-sonnet-4-20250514" for
      OpenRouter, "anthropic/claude-sonnet-4-20250514" for direct Anthropic,
      "openai/gpt-4o" for OpenAI, "google/gemini-2.0-flash-thinking-exp-01-21"
      for Google. The model string is passed directly to OpenCode without
      modification. IMPORTANT: Do not use reasoning models (o1, o3, deepseek-r1)
      as they output thinking process which breaks the agentic workflow.
      Recommended: anthropic/claude-sonnet-4-20250514, openai/gpt-4o,
      google/gemini-2.0-flash-001'
    required: false
    default: 'anthropic/claude-sonnet-4-20250514'
  problem_score_threshold:
    description: 'Minimum score (1-10) for reporting issues'
    required: false
    default: '5'
  blocking_score_threshold:
    description:
      'Minimum score (1-10) for issues to be considered blocking and fail the
      check (defaults to problem_score_threshold)'
    required: false
    default: ''
  review_timeout_minutes:
    description: 'Total timeout for entire review in minutes (5-120)'
    required: false
    default: '40'
  max_review_retries:
    description: 'Maximum number of retry attempts if review times out (0-3)'
    required: false
    default: '1'
  enable_web:
    description: 'Enable web search and fetch capabilities'
    required: false
    default: 'false'
  github_token:
    description:
      'GitHub token for API access. The default GITHUB_TOKEN works for most
      features. To auto-resolve review threads (mark as resolved in GitHub UI),
      use a PAT with repo scope.'
    required: true
    default: ${{ github.token }}
  enable_human_escalation:
    description:
      'Enable escalation to human reviewers for unresolved disputes (requires
      human_reviewers)'
    required: false
    default: 'false'
  human_reviewers:
    description:
      'Comma-separated list of GitHub usernames to tag on escalated disputes
      (e.g., "alice,bob")'
    required: false
    default: ''
  debug_logging:
    description:
      'Enable verbose debug logging of LLM activity, events, and responses'
    required: false
    default: 'false'
  injection_detection_enabled:
    description:
      'Enable prompt injection detection for external inputs (developer
      comments, questions)'
    required: false
    default: 'true'
  injection_verification_model:
    description:
      'OpenRouter model to use for LLM-based prompt injection verification (used
      as secondary check after pattern detection)'
    required: false
    default: 'openai/gpt-4o-mini'
  review_manual_trigger_enable_start_comment:
    description:
      'Post a comment when a manually-triggered review starts (via bot mention)'
    required: false
    default: 'true'
  review_manual_trigger_enable_end_comment:
    description:
      'Post a comment when a manually-triggered review completes (via bot
      mention)'
    required: false
    default: 'true'
  require_task_info_in_pr_desc:
    description:
      'Require the PR description to contain sufficient task information. If
      enabled and the description is empty or insufficient, the review will
      fail. The description can contain the task directly or link to files in
      the repo (e.g., markdown files) containing the task specification.'
    required: false
    default: 'true'

# Define your outputs here.
outputs:
  review_status:
    description:
      'Status of the review: completed, failed, or has_blocking_issues'
  issues_found:
    description: 'Number of issues found and reported'
  blocking_issues:
    description: 'Number of blocking issues (score >= blocking_score_threshold)'

runs:
  using: node20
  main: dist/index.js
